version: '3.8'

services:
  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: life-expectancy-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      - /app/__pycache__
    networks:
      - life-expectancy-network
    command: python app.py
    restart: unless-stopped

  # Frontend React App (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: life-expectancy-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules
    networks:
      - life-expectancy-network
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped

networks:
  life-expectancy-network:
    driver: bridge
